'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {createApplication,warehouseClient,healthContext}=require('../national/application');
const {createGateway}=require('../national/gateway');
const {validateInput}=require('../national/evidence');
function fixture(supply='public'){return{generated_at:'2026-09-17T00:00:00Z',supply:{type:supply},address:{status:'unresolved'},provider:{candidates:[],user_selected_pwsid:null},systems:[{pwsid:'010106001'}],gaps:[],audit:[],household_safety:{status:'not-determined'}};}
test('national production uses real warehouse counts rather than catalogue claims',async()=>{
 const e=createApplication({core:{lookup:async()=>fixture()},warehouse:{read:async p=>p==='/status'?{retained_source_records:42,published_archives:1,target_met:false,sources:{}}:{pwsid:'010106001',summaries:[{analyte:'LEAD',detects:1}],sources:[]}}});
 const x=await e.lookup({});assert.equal(x.coverage.observations.retained_source_records,42);assert.equal(x.occurrence[0].pwsid,'010106001');assert.equal(x.household_safety.status,'not-determined');assert.equal(x.health_context[0].title,'Lead');
});
test('warehouse outage is unavailable, never zero',async()=>{const x=await createApplication({warehouse:{read:async()=>{throw Error();}}}).status();assert.equal(x.observations.retained_source_records,null);assert.equal(x.observations.ingestion_status,'unavailable');});
test('private well does not borrow system observations',async()=>{const called=[];const e=createApplication({core:{lookup:async()=>fixture('private-well')},warehouse:{read:async p=>{called.push(p);return{retained_source_records:10,published_archives:1};}}});const r=await e.lookup({});assert.deepEqual(r.occurrence,[]);assert.deepEqual(called,['/status']);});
test('no health effect is attached merely to a non-detect',()=>assert.deepEqual(healthContext([{analyte:'LEAD',detects:0}]),[]));
test('warehouse rejects a mismatched identity',async()=>{const c=warehouseClient({base:'http://warehouse.example',fetchImpl:async()=>new Response(JSON.stringify({pwsid:'CA0000001',summaries:[],sources:[]}))});await assert.rejects(c.read('/pws/FL0000001'));});
test('warehouse public-resource cache is bounded and reuses concurrent requests',async()=>{let calls=0;const c=warehouseClient({base:'http://warehouse.example',fetchImpl:async()=>{calls++;return new Response(JSON.stringify({pwsid:'CA0000001',summaries:[],sources:[]}));}});await Promise.all([c.read('/pws/CA0000001'),c.read('/pws/CA0000001')]);assert.equal(calls,1);await assert.rejects(c.read('/../secret'));});
async function listen(server){await new Promise(r=>server.listen(0,'127.0.0.1',r));return server.address().port;}
async function close(server){await new Promise(r=>server.close(r));}
test('gateway preserves original auth Host and routes Seminole without touching original HTML',async()=>{
 let seen;const legacy=http.createServer((req,res)=>{seen={path:req.url,host:req.headers.host,xff:req.headers['x-forwarded-for']};res.writeHead(200,{'Content-Type':'text/plain'});res.end('legacy');});const p=await listen(legacy);const gateway=createGateway({legacyPort:p,engine:{status:async()=>({ok:true}),lookup:async x=>{validateInput(x);return{ok:true};}}});const q=await listen(gateway);try{const r=await fetch(`http://127.0.0.1:${q}/seminole?hello=1`);assert.equal(await r.text(),'legacy');assert.equal(seen.path,'/?hello=1');assert.equal(seen.host,`127.0.0.1:${q}`);const h=await fetch(`http://127.0.0.1:${q}/`);assert.match(await h.text(),/Check your address/);const s=await fetch(`http://127.0.0.1:${q}/api/national/status`);assert.deepEqual(await s.json(),{ok:true});const bad=await fetch(`http://127.0.0.1:${q}/api/national/lookup`,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://attacker.example'},body:'{}'});assert.equal(bad.status,403);}finally{await close(gateway);await close(legacy);}
});
test('national browser code compiles and uses no untrusted HTML insertion',()=>{const code=fs.readFileSync(path.join(__dirname,'../national/web/app.js'),'utf8');assert.doesNotThrow(()=>new Function(code));assert.doesNotMatch(code,/innerHTML/);});
const {normalizeFeature,createContext}=require('../national/context');
test('latest telemetry preserves old dates, provisional flags and non-concentration units',()=>{const x=normalizeFeature({id:'a',properties:{monitoring_location_id:'USGS-001',time:'2019-05-27T20:00:00Z',value:'6.2',unit_of_measure:'_FNU',approval_status:'Provisional',parameter_code:'63680'}},'2026-09-17T00:00:00Z');assert.equal(x.value,6.2);assert.equal(x.not_recent,true);assert.equal(x.household_match,false);assert.equal(x.approval_status,'Provisional');assert.equal(x.unit,'_FNU');});
test('missing telemetry is not zero',()=>{const x=normalizeFeature({properties:{monitoring_location_id:'USGS-001',time:'2026-01-01T00:00:00Z',value:null}},'2026-09-17T00:00:00Z');assert.equal(x.value,null);});
test('telemetry only queries fixed source and exposes pagination',async()=>{let target;const context=createContext({fetchImpl:async url=>{target=String(url);return new Response(JSON.stringify({features:[],links:[{rel:'next',href:'https://example.invalid/ignored'}]}));}});const x=await context({latitude:28.8,longitude:-81.2});assert.match(target,/^https:\/\/api.waterdata.usgs.gov\/ogcapi/);assert.equal(x.status,'partial');assert.equal(x.household_match,false);});
