'use strict';
// Synthetic fixtures: these tests are implementation checks, not national accuracy estimates.
const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../national/evidence'),S=require('../national/service');
const {createServer}=require('../national/server');
const input={street:'1 Synthetic Street',city:'Example',state:'NY'};
const hit={addressComponents:{state:'NY'},coordinates:{x:-74,y:41},matchedAddress:'SYNTHETIC TEST ADDRESS'};
const census={result:{addressMatches:[hit]}};
const feature=(id='NY1234567',more={})=>({attributes:{PWSID:id,PWS_Name:'Synthetic Utility',Data_Provider_Type:'State',...more}});
const measurement={value:'1',unit:'mg/L',sample_date:'2026-01-02',matrix:'water',chemical_basis:'element',quality_status:'accepted'};
const now=()=>new Date('2026-09-17T12:00:00Z');
const fixture=({geo=census,boundaries={features:[feature()]},federal={Results:{Systems:[{PWSID:'NY1234567',PWSName:'Synthetic Utility'}]}},fail=''}={})=>async url=>{const u=new URL(url);if(fail&&u.hostname.includes(fail))throw new Error('Synthetic outage');if(u.hostname.includes('census'))return geo;if(u.hostname==='services.arcgis.com')return boundaries;return federal;};
test('all 50 states DC and five territories are accepted without Florida defaults',()=>{assert.equal(E.REGION_CODES.length,56);assert.equal(new Set(E.REGION_CODES).size,56);for(const state of E.REGION_CODES)assert.equal(E.validateInput({...input,state}).state,state);});
for(const [name,patch]of Object.entries({badState:{state:'ZZ'},noAddress:{street:''},noCityOrZip:{city:''},invalidZip:{zip:'123'},shortID:{pwsid:'1234567'},longStreet:{street:'x'.repeat(181)},badSupply:{supply_type:'safe'},controlCharacter:{street:'x\u0000'},arrayStreet:{street:[]}}))test('input rejects '+name,()=>assert.throws(()=>E.validateInput({...input,...patch})));
test('bare PWSID lookup does not require a street',()=>assert.equal(E.validateInput({state:'NY',pwsid:'NY1234567'}).pwsid,'NY1234567'));
test('full IDs preserve namespaces and leading zeros',()=>{for(const id of ['NY1234567','FL1234567','090000023','NN3503048'])assert.ok(E.validPwsid(id));assert.notEqual('NY1234567','FL1234567');});
test('private well and public ID conflict is rejected',()=>assert.throws(()=>E.validateInput({...input,pwsid:'NY1234567',supply_type:'private-well'})));
test('numeric missing values are not zero',()=>{for(const x of ['',null,undefined,'NaN',Infinity,true,[]])assert.equal(E.finiteNumber(x),null);assert.equal(E.finiteNumber('0'),0);});
test('normalization retains original units and chemistry basis',()=>{const r=E.normalizeMeasurement(measurement);assert.equal(r.value_ug_l,1000);assert.equal(r.original.chemical_basis,'element');});
for(const [unit,value]of [['ug/L',1],['µg/L',1],['μg/L',1],['ng/L',.001]])test('converts '+unit,()=>assert.equal(E.normalizeMeasurement({...measurement,unit}).value_ug_l,value));
for(const value of ['<1','<=1','>1','>=1','≤1','≥1'])test('censored '+value+' is not an exact concentration',()=>{const r=E.normalizeMeasurement({...measurement,value});assert.equal(r.value_ug_l,null);assert.equal(r.eligible_for_numeric_analysis,false);assert.equal(r.reported_bound_ug_l,1000);});
test('ND and reporting limit units are retained',()=>{const r=E.normalizeMeasurement({...measurement,value:'ND',reporting_limit:'4',reporting_limit_unit:'ng/L'});assert.equal(r.reported_bound_ug_l,.004);assert.equal(r.value_ug_l,null);});
test('explicit censor bound is not overwritten by a separate reporting limit',()=>{
 const r=E.normalizeMeasurement({...measurement,value:'<1',reporting_limit:'10'});
 assert.equal(r.reported_bound_ug_l,1000);
 assert.equal(r.reporting_limit_ug_l,10000);
 assert.equal(r.bound_source,'reported-value');
 assert.equal(r.value_ug_l,null);
 assert.equal(r.eligible_for_numeric_analysis,false);
});
test('qualifier censor bound uses result units independently of reporting-limit units',()=>{
 const r=E.normalizeMeasurement({...measurement,value:'2',qualifier:'>',reporting_limit:'5',reporting_limit_unit:'ng/L'});
 assert.equal(r.reported_bound_ug_l,2000);
 assert.equal(r.reporting_limit_ug_l,.005);
 assert.equal(r.censor_operator,'>');
 assert.equal(r.bound_source,'reported-value');
 const noLimit=E.normalizeMeasurement({...measurement,value:'<1',reporting_limit_unit:'ng/L'});
 assert.equal(noLimit.reported_bound_ug_l,1000);
 assert.equal(noLimit.reporting_limit_ug_l,null);
});
test('invalid explicit censor bound cannot be silently replaced by a method reporting limit',()=>{
 const r=E.normalizeMeasurement({...measurement,value:'<invalid',reporting_limit:'10'});
 assert.equal(r.reported_bound_ug_l,null);
 assert.equal(r.reporting_limit_ug_l,10000);
 assert.equal(r.bound_source,null);
 assert.ok(r.issues.includes('censor-bound-unresolved'));
});
test('bare nondetect uses independently converted reporting limit as its bound',()=>{
 const r=E.normalizeMeasurement({...measurement,value:'ND',reporting_limit:'4',reporting_limit_unit:'ng/L'});
 assert.equal(r.reported_bound_ug_l,.004);
 assert.equal(r.reporting_limit_ug_l,.004);
 assert.equal(r.bound_source,'reporting-limit');
});
test('ND without a detection limit stays unresolved',()=>assert.ok(E.normalizeMeasurement({...measurement,value:'ND'}).issues.includes('reporting-limit-unresolved')));
test('unsupported ppm is not assumed mg/L',()=>assert.equal(E.normalizeMeasurement({...measurement,unit:'ppm'}).eligible_for_numeric_analysis,false));
test('unknown medium cannot become water evidence',()=>assert.equal(E.normalizeMeasurement({...measurement,matrix:'soil'}).eligible_for_numeric_analysis,false));
test('nitrate basis cannot be silently dropped',()=>assert.equal(E.normalizeMeasurement({...measurement,chemical_basis:''}).eligible_for_numeric_analysis,false));
test('invalid and future dates require review',()=>{for(const sample_date of ['2026-02-30','2029-01-01',''])assert.equal(E.normalizeMeasurement({...measurement,sample_date},'2026-09-17').eligible_for_numeric_analysis,false);});
test('unknown source QA is not accepted automatically',()=>assert.equal(E.normalizeMeasurement({...measurement,quality_status:'unknown'}).eligible_for_numeric_analysis,false));
test('conflicting qualifiers are rejected from analysis',()=>assert.ok(E.normalizeMeasurement({...measurement,value:'<1',qualifier:'>'}).issues.includes('conflicting-censor-qualifiers')));
test('negative and overflowing concentrations stay out of analysis',()=>{for(const value of ['-1','1e308'])assert.equal(E.normalizeMeasurement({...measurement,value}).eligible_for_numeric_analysis,false);});
test('wrong-state geocode is not accepted',()=>assert.equal(E.censusMatch(census,{state:'CA'}).status,'unresolved'));
test('multiple geocoder hits remain ambiguous',()=>assert.equal(E.censusMatch({result:{addressMatches:[hit,hit]}},input).status,'ambiguous'));
test('address interpolation is not rooftop or household proof',()=>{const r=E.censusMatch(census,input);assert.match(r.precision,/not-rooftop/);assert.equal(r.household_connection_verified,false);});
test('malformed geocoder response fails closed',()=>assert.throws(()=>E.censusMatch({},input)));
test('modeled boundary remains modeled even with a confirmed flag',()=>assert.equal(E.boundaryCandidates({features:[feature('NY1234567',{Data_Provider_Type:'EPA',Confirmed:'Yes'})]})[0].provenance,'modeled'));
test('model method overrides state-source label',()=>assert.equal(E.boundaryCandidates({features:[feature('NY1234567',{Model_Method:'Random forest'})]})[0].provenance,'modeled'));
test('unknown provenance does not become authoritative',()=>assert.equal(E.boundaryCandidates({features:[feature('NY1234567',{Data_Provider_Type:'Unknown'})]})[0].provenance,'unclassified'));
test('overlap preserves multiple candidates',()=>assert.equal(E.boundaryCandidates({features:[feature(),feature('NY7654321')]}).length,2));
test('duplicate copies do not add independent votes',()=>assert.equal(E.boundaryCandidates({features:[feature(),feature()]}).length,1));
test('truncated boundary responses fail closed',()=>assert.throws(()=>E.boundaryCandidates({features:[feature()],exceededTransferLimit:true})));
test('boundary malformed full ID is not repaired by guessing',()=>assert.throws(()=>E.boundaryCandidates({features:[feature('1234567')]})));
test('ECHO schema change is not a zero-result finding',()=>assert.throws(()=>E.echoRows({Results:{NewSchema:[]}},'NY1234567')));
test('ECHO exact-ID matching rejects another state',()=>assert.equal(E.echoRows({Results:{Systems:[{PWSID:'FL1234567'}]}},'NY1234567').length,0));
test('ECHO zero count must be explicit',()=>assert.deepEqual(E.echoRows({Results:{QueryRows:'0'}},'NY1234567'),[]));
test('query IDs are found recursively and numeric IDs preserved',()=>assert.equal(E.queryId({Results:{nested:{QueryID:12345}}}),'12345'));
test('canonical hashes ignore object property order',()=>assert.equal(E.fingerprint({a:1,b:2}),E.fingerprint({b:2,a:1})));
for(const url of ['http://127.0.0.1/','https://echodata.epa.gov.evil.test/','https://echodata.epa.gov/other','https://x:y@echodata.epa.gov/echo/sdw_rest_services.get_systems'])test('unapproved URL rejected '+url,()=>assert.throws(()=>S.safeTarget(url)));
test('transport rejects HTTP error as unavailable',async()=>{const t=S.transport({fetchImpl:async()=>new Response('down',{status:503})});await assert.rejects(t(S.ENDPOINTS.systems));});
test('transport enforces byte limits',async()=>{const t=S.transport({maxBytes:5,fetchImpl:async()=>new Response('{"value":123}')});await assert.rejects(t(S.ENDPOINTS.systems));});
test('transport rejects JSON error payloads',async()=>{const t=S.transport({fetchImpl:async()=>new Response('{"error":"bad query"}')});await assert.rejects(t(S.ENDPOINTS.systems));});
test('complete fixture request returns evidence without a safety guarantee',async()=>{const r=await S.createEngine({request:fixture(),now}).lookup(input);assert.equal(r.systems[0].status,'records-returned');assert.equal(r.household_safety.status,'not-determined');assert.deepEqual(r.household_safety.measured_concentrations,[]);});
test('empty boundary never classifies property as private well',async()=>{const r=await S.createEngine({request:fixture({boundaries:{features:[]}}),now}).lookup(input);assert.equal(r.supply.type,'unknown');assert.equal(r.provider.status,'unresolved');});
test('private-well requests never borrow public utility records',async()=>{const r=await S.createEngine({request:fixture(),now}).lookup({...input,supply_type:'private-well'});assert.deepEqual(r.systems,[]);assert.equal(r.household_safety.status,'not-determined');});
test('Census outage does not block a user-selected public system',async()=>{const r=await S.createEngine({request:fixture({fail:'census'}),now}).lookup({...input,pwsid:'NY1234567'});assert.equal(r.address.status,'unavailable');assert.equal(r.systems[0].status,'records-returned');});
test('user-selected ID conflict remains explicit',async()=>{const r=await S.createEngine({request:fixture(),now}).lookup({...input,pwsid:'NY7654321'});assert.equal(r.provider.conflict,true);});
test('more than four candidates do not silently yield a winner',async()=>{const r=await S.createEngine({request:fixture({boundaries:{features:[1,2,3,4,5].map(i=>feature('NY'+String(i).padStart(7,'0')))}}),now}).lookup(input);assert.equal(r.provider.candidates.length,5);assert.deepEqual(r.systems,[]);});
test('source catalog size is not claimed locally ingested',()=>assert.equal(S.createEngine().status().national_unique_observations_ingested,'0'));
async function withServer(fn){const server=createServer({engine:S.createEngine({request:fixture(),now})});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{await fn('http://127.0.0.1:'+server.address().port);}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}}
test('HTTP lookup is wired and has no-store headers',async()=>withServer(async base=>{const r=await fetch(base+'/api/national/lookup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal((await r.json()).household_safety.status,'not-determined');}));
test('HTTP rejects foreign origin',async()=>withServer(async base=>{const r=await fetch(base+'/api/national/lookup',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://invalid.example'},body:'{}'});assert.equal(r.status,403);}));
test('HTTP rejects non-JSON content',async()=>withServer(async base=>{const r=await fetch(base+'/api/national/lookup',{method:'POST',body:'abc'});assert.equal(r.status,415);}));
test('HTTP rejects malformed JSON',async()=>withServer(async base=>{const r=await fetch(base+'/api/national/lookup',{method:'POST',headers:{'Content-Type':'application/json'},body:'{'});assert.equal(r.status,400);}));
test('browser interface discloses variable coverage and limits of household evidence',async()=>withServer(async base=>{const r=await fetch(base+'/national');assert.equal(r.status,200);const html=await r.text();assert.match(html,/current drinking-water instructions/);assert.match(html,/utility or local health department/);assert.doesNotMatch(html,/100% accurate|certified safe/);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);}));
