'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {buildResidentReport,comparison}=require('../national/resident');
const {HTML,CLIENT}=require('../national/ui');
const {createEngine,ENDPOINTS}=require('../national/service');
const {validateInput,censusMatch}=require('../national/evidence');
const {createPropertyContext,sourceReader,streetKey}=require('../national/property');
const {getHealthContext}=require('../national/health_context');
const source={id:'syr4',url:'https://www.epa.gov/dwsixyearreview'},summary={analyte:'Arsenic',scope:'system-monitoring',source_id:'syr4',unit:'µg/L',n:20,detects:8,nondetects:12,min_detect:2,max_detect:12,first_date:'2012-01-01',last_date:'2019-01-01',invalid_identity_date:0};
function report(){return {address:{status:'matched',matched_address:'SYNTHETIC FIXTURE'},supply:{type:'public'},provider:{candidates:[{pwsid:'NY1234567',name:'Fixture Water'}]},systems:[{pwsid:'NY1234567',archive:{summaries:[summary],sources:[source],compliance:{status:'records-returned',distinct_violation_ids:1,records:[{VIOLATION_ID:'01',IS_HEALTH_BASED_IND:'Y',VIOLATION_STATUS:'Resolved',NON_COMPL_PER_BEGIN_DATE:'01/01/2020',code_descriptions:{VIOLATION_CODE:'Test violation'}},{VIOLATION_ID:'01',IS_HEALTH_BASED_IND:'Y',VIOLATION_STATUS:'Resolved',code_descriptions:{VIOLATION_CODE:'Test violation'}},{ENFORCEMENT_ID:'2',VIOLATION_ID:'',IS_HEALTH_BASED_IND:'Y',VIOLATION_STATUS:'Unresolved'}],source:{documentation_url:'https://echo.epa.gov/'}}}}],generated_at:'2026-09-18T00:00:00Z'};}
test('one full address does not require a second state or utility ID field',async()=>{const input=validateInput({address:'100 Synthetic St, Example, NY 10001'});assert.equal(input.state,'');const calls=[];const result=await createEngine({request:async(url)=>{calls.push(url);if(url.startsWith(ENDPOINTS.censusOneLine))return {result:{addressMatches:[{matchedAddress:input.address,addressComponents:{state:'NY'},coordinates:{x:-74,y:41},geographies:{Counties:[{NAME:'Fixture County',GEOID:'00000'}]}}]}};return {features:[]};}}).lookup(input);assert.equal(result.address.state,'NY');assert.equal(result.address.geography.county.name,'Fixture County');assert.ok(calls[0].includes('onelineaddress'));assert.ok(result.resident_report.actions.length);});
test('an unrecognized country/state and ambiguous address cannot select a house',()=>{assert.equal(censusMatch({result:{addressMatches:[{addressComponents:{state:'ON'},coordinates:{x:-75,y:45}}]}},{state:''}).status,'unresolved');const h={addressComponents:{state:'NY'},matchedAddress:'Fixture',coordinates:{x:-74,y:41}};const r=censusMatch({result:{addressMatches:[h,h]}},{state:''});assert.equal(r.status,'ambiguous');assert.equal(r.candidates.length,2);assert.equal(r.latitude,undefined);});
test('Census aliases for the same numbered address and TIGER point do not trap a resident in repeated choices',()=>{
 const a={matchedAddress:'100 SAINT FIXTURE ST, EXAMPLE, NY, 10001',addressComponents:{state:'NY',city:'EXAMPLE',zip:'10001'},coordinates:{x:-74,y:41},tigerLine:{tigerLineId:'12345',side:'R'}},b={...a,matchedAddress:'100 ST FIXTURE ST, EXAMPLE, NY, 10001'};
 const match=(x,y)=>censusMatch({result:{addressMatches:[x,y]}},{state:''});
 assert.equal(match(a,b).status,'matched');assert.equal(match(a,b).household_connection_verified,false);
 for(const changed of [{...b,coordinates:{x:-74.001,y:41}},{...b,matchedAddress:'102 ST FIXTURE ST, EXAMPLE, NY, 10001'},{...b,tigerLine:{tigerLineId:'999',side:'R'}},{...b,tigerLine:{tigerLineId:'12345',side:'L'}},{...b,addressComponents:{...b.addressComponents,zip:'10002'}}])assert.equal(match(a,changed).status,'ambiguous');
});
test('comparisons preserve sampling scope, chemical basis and units',()=>{assert.equal(comparison(summary).above_reference,true);assert.equal(comparison({...summary,unit:'mg/L',max_detect:.012}).above_reference,true);assert.equal(comparison({...summary,unit:'ng/L',max_detect:12000}).above_reference,true);assert.equal(comparison({...summary,scope:'source-water'}),null);assert.equal(comparison({...summary,unit:'pCi/L'}),null);assert.equal(comparison({...summary,max_detect:null}),null);assert.equal(comparison({...summary,analyte:'Nitrate'}),null);assert.equal(comparison({...summary,analyte:'Nitrate as N',unit:'mg/L',max_detect:11}).above_reference,true);assert.equal(comparison({...summary,analyte:'Lead'}),null);});
test('health explanations preserve chemical form and isomer identity',()=>{
 assert.equal(getHealthContext('1,4-dioxane').matched,true);assert.equal(getHealthContext('1,3-dioxane').matched,false);
 assert.equal(getHealthContext('total chromium').matched,true);assert.equal(getHealthContext('hexavalent chromium').matched,false);
 assert.equal(getHealthContext('inorganic mercury').matched,true);assert.equal(getHealthContext('methylmercury').matched,false);
 assert.equal(getHealthContext('chlorite').matched,true);assert.equal(getHealthContext('chlorate').matched,false);
 const manganese=getHealthContext('manganese');assert.equal(manganese.scope,'general-contaminant-information-not-household-risk');assert.match(manganese.sources[0].url,/iris\.epa\.gov/);
 assert.equal(comparison({...summary,analyte:'manganese',max_detect:106}),null);
});
test('historical compliance events are deduplicated and never become current alerts',()=>{const r=buildResidentReport(report());assert.equal(r.compliance[0].issues.length,1);assert.equal(r.current_advisories_checked,false);assert.equal(r.household_safety,'not-determined');assert.ok(r.findings[0].health.text);assert.ok(r.actions.length);assert.doesNotMatch(JSON.stringify(r.actions),/unresolved/);});
test('private well never inherits utility chemistry, compliance or health findings',()=>{const d=report();d.supply.type='private-well';const r=buildResidentReport(d);assert.deepEqual(r.findings,[]);assert.deepEqual(r.providers,[]);assert.deepEqual(r.compliance,[]);assert.match(r.actions[0].text,/annual/);});
test('source outages still provide concrete supported next steps without a fabricated finding',()=>{const r=buildResidentReport({address:{status:'unavailable'},provider:{candidates:[]},systems:[],supply:{type:'unknown'}});assert.ok(r.actions.length>=2);assert.match(r.headline,/address/);assert.equal(r.findings.length,0);assert.equal(r.household_safety,'not-determined');});
test('property lookup isolates failures and does not attach a neighboring service line',async()=>{const result=await createPropertyContext({request:async url=>{if(url.includes('monitoring-locations'))throw Error('outage');if(url.includes('efpoints'))return {features:[]};if(url.includes('/api/views/'))return {id:'jqfp-uff7',rowsUpdatedAt:1769786025,columns:[]};return [{address:'102 FAKE STREET',material:'Lead',record_ty:'Fixture',tbbl:'1000010001'}];}})({state:'NY',latitude:40.71,longitude:-74.0,matched_address:'100 FAKE ST, NEW YORK, NY'},{supplyType:'public'});assert.equal(result.wells.status,'unavailable');assert.equal(result.cleanup_sites.status,'no-records-in-search');assert.equal(result.service_line.household_match,false);assert.equal(result.service_line.records.length,0);assert.equal(streetKey('100 E 74TH ST'),streetKey('100 EAST 74 STREET'));});
test('property queries reject redirects and unapproved destinations',async()=>{await assert.rejects(sourceReader()('https://example.org/'));let called;await sourceReader({fetchImpl:async(u,opts)=>{called=opts;return new Response('[]');}})('https://data.cityofnewyork.us/resource/jqfp-uff7.json');assert.equal(called.redirect,'error');});
test('the home page asks for one address and contains no ingestion or schema dashboard',()=>{assert.match(HTML,/for="address"/);assert.match(HTML,/role="status" aria-live="polite"/);assert.match(HTML,/prefers-reduced-motion/);assert.doesNotMatch(HTML,/PWSID|ingestion|dataset-count|Postgres|archive-count|name="state"/);assert.doesNotMatch(CLIENT,/innerHTML|insertAdjacentHTML|JSON\.stringify\(data|createElement\('pre'/);assert.doesNotThrow(()=>new Function(CLIENT));});
test('distributed resident client submits an address, renders health context and resets private-well selection',async()=>{
 const vm=require('node:vm');class Element{constructor(tag){this.tag=tag;this.children=[];this.listeners={};this.attrs={};this.value='';this.disabled=false;this._text='';}set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(x=>x.textContent).join(' ');}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this._text='';this.children=[...nodes];}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,v){this.listeners[k]=v;}focus(){}scrollIntoView(){}reportValidity(){return true;}}
 const ids=['lookup-form','address','supply','lookup-button','message','results','how-it-works','progress'];const nodes=Object.fromEntries(ids.map(id=>[id,new Element('div')]));nodes.address.value='100 Synthetic Street, Example, NY';nodes.supply.value='public';const calls=[];
 vm.runInNewContext(CLIENT,{document:{getElementById:id=>nodes[id],createElement:tag=>new Element(tag)},URL,Date,Map,AbortController,setTimeout,clearTimeout,fetch:async(url,opts)=>{const body=JSON.parse(opts.body);calls.push(body);const d=report();d.supply.type=body.supply_type;d.resident_report=buildResidentReport(d);return {ok:true,json:async()=>d};}});
 await nodes['lookup-form'].listeners.submit({preventDefault(){}});for(let i=0;i<4;i++)await new Promise(setImmediate);
 assert.equal(calls[0].address,nodes.address.value);assert.equal(calls[0].include_environment,true);assert.match(nodes.results.textContent,/What this means for your health/);assert.match(nodes.results.textContent,/Arsenic/);assert.match(nodes.results.textContent,/Resolved/);assert.doesNotMatch(nodes.results.textContent,/sha256|raw_rows|syr4|trained_prediction/);
 nodes.supply.value='private-well';nodes.supply.listeners.change();nodes['lookup-form'].listeners.submit({preventDefault(){}});for(let i=0;i<4;i++)await new Promise(setImmediate);assert.match(nodes.results.textContent,/What to test in your well/);assert.doesNotMatch(nodes.results.textContent,/Arsenic|Fixture Water/);assert.equal(nodes['lookup-button'].disabled,false);assert.equal(nodes.results.attrs['aria-busy'],'false');
});
