'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {ROOT,FIELDS,COUNTS,normalize,createServiceLines,sourceReader,target,withServiceLines}=require('../national/service_lines');
const ID='TX2270001',NOW=Date.parse('2026-09-18T00:00:00Z');
function row(extra={}){return {PWSID:ID,PWS_NAME:'Example municipal utility',SL_RPT_STATUS:'Reported',TOTAL_NUM_SERVICE_LINES_REPORTED:10,NUM_LEAD_SERVICE_LINES:1,NUM_GALVANIZED_REQUIRING_REPLACEMENT_SL:2,NUM_LEAD_STATUS_UNKNOWN_SL:3,NUM_NONLEAD_SERVICE_LINES:4,...extra};}
function fixture(result={features:[{attributes:row()}]}){let calls=0;return {get calls(){return calls;},async request(u){calls++;if(u.startsWith(ROOT+'?'))return {tables:[{id:477,name:'CWS_CompleteTable_20260831'}]};if(!u.includes('/query?'))return {fields:FIELDS.map(name=>({name,type:Object.values(COUNTS).includes(name)?'esriFieldTypeDouble':'esriFieldTypeString'})),editingInfo:{lastEditDate:NOW-86400000}};return result;}};}
test('verified utility counts remain separate from household material and chemistry',async()=>{const f=fixture(),get=createServiceLines({request:f.request,now:()=>NOW});const r=await get({pwsids:[ID]});assert.equal(r.status,'records-returned');assert.equal(r.records[0].counts.lead,1);assert.equal(r.records[0].household_material_verified,false);assert.equal(r.records[0].household_lead_concentration,null);assert.equal(r.records[0].category_total_matches,true);assert.equal(r.source_table,'CWS_CompleteTable_20260831');assert.equal(f.calls,3);assert.equal(r.comprehensive,false);});
test('unreported counts stay null and explicit zero stays zero',()=>{const r=normalize(row({NUM_LEAD_SERVICE_LINES:null,NUM_NONLEAD_SERVICE_LINES:0}),[ID]);assert.equal(r.counts.lead,null);assert.equal(r.counts.non_lead,0);assert.equal(r.category_total_matches,null);});
test('bad counts and identities fail closed',()=>{for(const value of [-1,1.2,'10',NaN,Infinity,undefined])assert.throws(()=>normalize(row({NUM_LEAD_SERVICE_LINES:value}),[ID]));assert.throws(()=>normalize(row({PWSID:'XX9999999'}),[ID]));});
test('private wells and invalid IDs do not trigger upstream lookup',async()=>{let calls=0;const get=createServiceLines({request:async()=>{calls++;throw Error();}});assert.equal((await get({pwsids:[ID],supplyType:'private-well'})).status,'not-applicable-private-well');for(const ids of [[],['TX1\' OR 1=1'],['tx2270001']])await get({pwsids:ids});assert.equal(calls,0);});
test('truncation, duplicate rows, and source errors do not become empty successes',async()=>{for(const result of [{features:[],exceededTransferLimit:true},{features:[{attributes:row()},{attributes:row()}]},{error:{code:500}}]){const f=fixture(result),get=createServiceLines({request:f.request,now:()=>NOW});assert.equal((await get({pwsids:[ID]})).status,'unavailable');}});
test('no matching inventory is not a non-lead finding',async()=>{const f=fixture({features:[]});const r=await createServiceLines({request:f.request,now:()=>NOW})({pwsids:[ID]});assert.equal(r.status,'no-matching-inventory');assert.equal(r.household_material_verified,false);});
test('cache retains acquisition date and cannot be corrupted by callers',async()=>{const f=fixture(),get=createServiceLines({request:f.request,now:()=>NOW});const a=await get({pwsids:[ID]});a.records[0].counts.lead=999;const b=await get({pwsids:[ID]});assert.equal(b.records[0].counts.lead,1);assert.equal(f.calls,3);assert.equal(a.retrieved_at,b.retrieved_at);});
test('source redirect and response-size boundaries are enforced',async()=>{for(const bad of ['http://127.0.0.1:8080','https://evil.example/'+ROOT,ROOT+'/0/query/extra',ROOT+'#a',ROOT.replace('services.arcgis','secret@services.arcgis')])assert.throws(()=>target(bad));let opts;const get=sourceReader({fetchImpl:async(u,o)=>{opts=o;return new Response('x'.repeat(21));},maxBytes:20});await assert.rejects(get(ROOT+'?f=json'));assert.equal(opts.redirect,'error');});
test('report enrichment preserves existing notices, property record and no-safety conclusion',async()=>{const f=fixture(),inv=await createServiceLines({request:f.request,now:()=>NOW})({pwsids:[ID]});const data={supply:{type:'public'},systems:[{pwsid:ID}],resident_report:{actions:[{title:'Read immediate notice'}],service_line:{status:'address-record-match'},household_safety:'not-determined'},household_safety:{status:'not-determined'}};const engine=withServiceLines({lookup:async()=>data,status:async()=>({coverage_verified:false})},{lookup:async()=>inv});const r=await engine.lookup({});assert.equal(r.resident_report.actions[0].title,'Read immediate notice');assert.equal(r.resident_report.actions.length,2);assert.match(r.resident_report.actions[1].text,/does not identify the pipe serving your home/);assert.equal(r.resident_report.service_line.status,'address-record-match');assert.equal(r.household_safety.status,'not-determined');assert.equal((await engine.status()).coverage_verified,false);});
