'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const {mkdtemp,rm,writeFile}=require('node:fs/promises');const {join}=require('node:path');const {tmpdir}=require('node:os');const {spawnSync}=require('node:child_process');
const {normalize,date,identifyMember}=require('../national/normalization');
const {createWarehouse}=require('../national/warehouse');
const {importArchive,approved,discoverUcmr}=require('../national/sync');
const sample={PWSID:'NY0000001',PWSName:'Fixture utility',FacilityID:'001',SamplePointID:'EP1',SamplePointType:'EP',SampleID:'S1',CollectionDate:'1/15/2025',Contaminant:'PFOA',MRL:'0.004',Units:'µg/L',MethodID:'EPA 533',AnalyticalResultsSign:'<',AnalyticalResultValue:'',State:'NY'};
test('real EPA UCMR plural qualifier, CP1252 unit and blank nondetect never become zero',()=>{const r=normalize('ucmr5','observation',sample);assert.equal(r.pwsid,'NY0000001');assert.equal(r.data.value,null);assert.equal(r.data.censored,true);assert.equal(r.data.reporting_limit,0.004);assert.equal(r.data.unit,'µg/L');assert.equal(r.data.analytical_method,'EPA 533');});
test('explicit UCMR censor bound remains distinct from method reporting limit',()=>{const r=normalize('ucmr5','observation',{...sample,AnalyticalResultValue:'1',MRL:'10'});assert.equal(r.data.reported_bound,1);assert.equal(r.data.reporting_limit,10);assert.equal(r.data.value,null);});
test('sample identity preserves event/analyte/method and federal leading zeros',()=>{const a=normalize('ucmr5','observation',{...sample,PWSID:'010106001'});assert.equal(a.pwsid,'010106001');assert.notEqual(a.record_key,normalize('ucmr5','observation',{...sample,PWSID:'010106001',SampleID:'S2'}).record_key);assert.throws(()=>normalize('ucmr5','observation',{...sample,SampleID:''}),/identity/);assert.throws(()=>normalize('ucmr5','observation',{...sample,PWSID:'1234567'}),/PWSID/);});
test('date normalization rejects invalid calendar dates and ambiguous data',()=>{assert.equal(date('02/29/2024'),'2024-02-29');assert.equal(date('02/29/2025'),null);assert.equal(date('31/12/2024'),null);assert.throws(()=>normalize('ucmr5','observation',{...sample,CollectionDate:'2/30/2025'}),/date/);});
test('detected results use supplied units and do not infer legal exceedance',()=>{const r=normalize('ucmr5','observation',{...sample,AnalyticalResultsSign:'=',AnalyticalResultValue:'0.005'});assert.equal(r.data.value,0.005);assert.equal(r.data.censored,false);assert.equal(r.data.compliance,undefined);assert.throws(()=>normalize('ucmr5','observation',{...sample,AnalyticalResultsSign:'?',AnalyticalResultValue:'1'}),/qualifier/);});
test('violation-enforcement records retain full federal ID and actual noncompliance dates',()=>{const r=normalize('sdwis-violations','violation',{PWSID:'NY0000001',VIOLATION_ID:'V1',ENFORCEMENT_ID:'E1',NON_COMPL_PER_BEGIN_DATE:'12/1/2022',NON_COMPL_PER_END_DATE:'1/1/2023',CALCULATED_RTC_DATE:'3/1/2023',IS_HEALTH_BASED_IND:'Y'});assert.equal(r.data.compliance_period_begin,'2022-12-01');assert.equal(r.data.returned_to_compliance,'2023-03-01');assert.equal(r.data.health_based,true);});
test('official systems with missing names preserve identity without inventing a utility name',()=>{const r=normalize('sdwis','system',{PWSID:'NY0000001',PWS_NAME:'',STATE_CODE:'NY'});assert.equal(r.data.name,'NY0000001');assert.equal(r.data.name_reported,false);});
test('unconfigured warehouse returns honest zero/no connection without database call',async()=>{const w=createWarehouse({connectionString:''});assert.equal(await w.initialize(),false);assert.equal((await w.status()).status,'not-connected');assert.equal((await w.lookupSystem('NY0000001')).status,'not-connected');assert.deepEqual(await w.searchSystems({state:'NY'}),[]);await w.close();});
test('download allowlist rejects credentials, non-HTTPS and foreign redirect origins',()=>{for(const x of ['http://www.epa.gov/a','https://example.com/a','https://user:pass@www.epa.gov/a'])assert.throws(()=>approved(x));assert.equal(approved('https://www.epa.gov/a').hostname,'www.epa.gov');});
test('UCMR discovery selects whole dataset, excluding duplicate state and method archives',async()=>{const result=await discoverUcmr(async()=>new Response('<a href="/system/files/other-files/2023-08/ucmr5-occurrence-data-by-state.zip"></a><a href="/system/files/other-files/2023-08/ucmr5-occurrence-data.zip"></a>'));assert.equal(result,'https://www.epa.gov/system/files/other-files/2023-08/ucmr5-occurrence-data.zip');});
test('archive streams CP1252 rows, ignores companion tables, validates completion',async()=>{const dir=await mkdtemp(join(tmpdir(),'national-test-'));try{const file=join(dir,'fixture.zip');const script=`import zipfile,sys,json\nr=json.loads(sys.argv[2])\nwith zipfile.ZipFile(sys.argv[1],'w') as z:\n z.writestr('UCMR5_All.txt',('\\t'.join(r)+'\\r\\n'+'\\t'.join(r.values())+'\\r\\n').encode('cp1252'))\n z.writestr('UCMR5_ZIPCodes.txt','PWSID\\tZIP\\nNY0000001\\t10001\\n')\n`;const result=spawnSync('python3',['-c',script,file,JSON.stringify(sample)]);assert.equal(result.status,0,result.stderr?.toString());const batches=[];const meta=await importArchive(file,'ucmr5',{batch:async r=>batches.push(r)},{batchSize:1});assert.equal(meta.source_rows,1);assert.equal(batches[0][0].data.censored,true);assert.equal(batches[0][0].data.unit,'µg/L');}finally{await rm(dir,{recursive:true,force:true});}});
test('malformed or unexpected ZIP cannot publish an empty success',async()=>{const dir=await mkdtemp(join(tmpdir(),'national-test-'));try{const file=join(dir,'fixture.zip');spawnSync('python3',['-c',"import zipfile,sys\nwith zipfile.ZipFile(sys.argv[1],'w') as z:z.writestr('other.csv','wrong,header\\na,b\\n')",file]);await assert.rejects(importArchive(file,'ucmr5',{batch:async()=>{}}),/ARCHIVE_PARSE_FAILED/);}finally{await rm(dir,{recursive:true,force:true});}});
// Real PostgreSQL integration is intentionally opt-in; use a dedicated test database.
test('Postgres atomic snapshots, idempotency, lock, query, counts and failure retention',{skip:!process.env.TEST_DATABASE_URL},async()=>{
 const {Pool}=require('pg');const pool=new Pool({connectionString:process.env.TEST_DATABASE_URL,max:5,statement_timeout:20000});
 const w=createWarehouse({pool});
 try{
  await pool.query('DROP SCHEMA IF EXISTS national_water CASCADE');await w.initialize();
  const a=await w.beginImport('ucmr5','https://www.epa.gov/fixture.zip');assert.ok(a);
  const locked=await w.beginImport('ucmr5','https://www.epa.gov/fixture.zip');assert.equal(locked,null);
  const observation=normalize('ucmr5','observation',sample);
  await a.batch([observation,observation]);await a.batch([observation]);
  assert.equal((await w.status()).national_unique_observations_ingested,'0');
  assert.equal((await w.lookupSystem('NY0000001')).observations.length,0);
  await a.metadata({sha256:'a'.repeat(64),bytes:100,modified:'2026-08-28'});await a.publish();
  let status=await w.status();assert.equal(status.national_unique_observations_ingested,'1');assert.equal(status.sources[0].source_rows,'3');
  const found=await w.lookupSystem('NY0000001');assert.equal(found.observations.length,1);assert.equal(found.observations[0].value,null);assert.equal(found.observation_summary[0].non_detects,'1');assert.equal(found.observation_summary[0].maximum_detected,null);
  const failed=await w.beginImport('ucmr5','https://www.epa.gov/new.zip');await failed.batch([normalize('ucmr5','observation',{...sample,SampleID:'S2'})]);await failed.fail('TEST_FAILURE');
  status=await w.status();assert.equal(status.national_unique_observations_ingested,'1');assert.equal(status.sources[0].latest_attempt.status,'failed');assert.equal((await w.lookupSystem('NY0000001')).observations[0].sample_id,'S1');
  const sys=await w.beginImport('sdwis','https://echo.epa.gov/fixture.zip');await sys.batch([normalize('sdwis','system',{PWSID:'NY0000001',PWS_NAME:'Fixture system',STATE_CODE:'NY',PWS_ACTIVITY_CODE:'A'})]);await sys.publish();assert.equal((await w.searchSystems({state:'NY',query:'Fixture'}))[0].pwsid,'NY0000001');
  const replacement=await w.beginImport('ucmr5','https://www.epa.gov/new.zip');await replacement.batch([normalize('ucmr5','observation',{...sample,SampleID:'S2',AnalyticalResultsSign:'=',AnalyticalResultValue:'0.02'})]);await replacement.publish();assert.equal((await w.lookupSystem('NY0000001')).observations[0].sample_id,'S2');assert.equal((await w.status()).national_unique_observations_ingested,'1');
  const conflicts=await w.beginImport('ucmr5','https://www.epa.gov/new.zip');await conflicts.batch([observation]);await assert.rejects(conflicts.batch([{...observation,data:{...observation.data,value:1}}]));await conflicts.fail('TEST_CONFLICT');assert.equal((await w.lookupSystem('NY0000001')).observations[0].sample_id,'S2');
  const empty=await w.beginImport('ucmr5','https://www.epa.gov/empty.zip');await assert.rejects(empty.publish(),/EMPTY_SOURCE_IMPORT/);
  status=await w.status();assert.equal(status.sources.find(s=>s.source==='ucmr5').latest_attempt.status,'failed');assert.equal(status.sources.find(s=>s.source==='ucmr5').latest_attempt.error_code,'EMPTY_SOURCE_IMPORT');
  assert.equal((await w.lookupSystem('NY0000001')).observations[0].sample_id,'S2');
  const retry=await w.beginImport('ucmr5','https://www.epa.gov/retry.zip');assert.ok(retry);await retry.fail('END_TEST');
 }finally{await pool.query('DROP SCHEMA IF EXISTS national_water CASCADE');await pool.end();}
});
